Repository CityofToronto/bdit_data-sources, pull requests merged in 2023-11, with the labels that each got.

#751 Choose the failure alerts' slack channel based on the running DAG's location
  dags/dag_functions.py
Labels: enhancement, Airflow

#757 Update broken HERE doc links
  here/README.md
Labels: Documentation

#735 717 miovision partition volumes and daily summary
  dags/eoy_create_tables.py
  dags/pull_miovision.py
  volumes/miovision/api/intersection_tmc.py
  volumes/miovision/sql/create-table-volumes.sql
  volumes/miovision/sql/create-table-volumes_15min.sql
  volumes/miovision/sql/create-table-volumes_15min_mvt.sql
  volumes/miovision/sql/create-table-volumes_daily.sql
  volumes/miovision/sql/function-aggregate-volumes_15min.sql
  volumes/miovision/sql/function-aggregate-volumes_daily.sql
  volumes/miovision/sql/function-create_mm_nested_volumes_partitions.sql
  volumes/miovision/sql/function-create_yyyy_volumes_15min_partition.sql
  volumes/miovision/sql/function-create_yyyy_volumes_partition.sql
  volumes/miovision/sql/function_create_volume_table.sql
  volumes/miovision/sql/trigger-volumes_insert_trigger.sql
  volumes/miovision/sql/update-mio_volumes15min_mvt_partitioning.sql
  volumes/miovision/sql/update-mio_volumes15min_partitioning.sql
  volumes/miovision/sql/update-mio_volumes_partitioning.sql
Labels: Miovision

#756 Fix typo, add link to readme
  README.md
Labels: Documentation

#762 #761 remove unused pd.read_sql function
  volumes/vds/py/vds_functions.py
Labels: RESCU

#749 744 miovision DST fix
  volumes/miovision/api/intersection_tmc.py
Labels: bug, Miovision

#773 #772 add a comma to vds_pull_vdsvehicledata
  dags/vds_pull_vdsvehicledata.py
Labels: bug

#723 Miovision `classification_uid` 7 is for bikes in the crosswalk
  volumes/miovision/README.md
Labels: Miovision, Documentation

#763 752 miovision standardize definition of day
  volumes/miovision/sql/create-table-volumes_daily.sql
  volumes/miovision/sql/function-aggregate-volumes_15min.sql
  volumes/miovision/sql/function-aggregate-volumes_15min_mvt.sql
  volumes/miovision/sql/function-aggregate-volumes_15min_mvt_single_intersection.sql
  volumes/miovision/sql/function-aggregate-volumes_daily.sql
Labels: Miovision
