Repository CityofToronto/bdit_data-sources, pull requests merged in 2023-04, with the labels that each got.

#567 Add simple `parking/` readme
  parking/readme.md
Labels: Documentation

#557 Simplify the main readme
  README.md
  assets/traffic_signals/README.md
  bluetooth/README.md
  inrix/README.md
  volumes/README.md
  volumes/miovision/README.md
  volumes/rescu/README.md
  wys/readme.md
Labels: Documentation

#558 Here valid range
  here/README.md
  here/traffic/sql/create_here_valid_range.sql
Labels: here, Documentation

#578 Run bigdata GCC puller tasks on the dev server only
  dags/gcc_layers_pull.py
Labels: enhancement, gis

#584 Format directory links consistently
  README.md
Labels: Documentation
