Repository CityofToronto/bdit_data-sources, pull requests merged in 2024-04, with the labels that each got.

#916 #906 remove new line from comment
  dags/common_tasks.py
Labels: bug, collisions

#904 Upgrade Airflow to 2_8_4
  constraints.txt
  requirements.in
  requirements.txt
Labels: dependencies, Airflow

#873 #872 update volumes_15min_mvt pkey
  volumes/miovision/sql/table/create-table-volumes_15min_mvt.sql
Labels: Miovision

#928 927 add a replicator health check
  dags/replicator_table_check.py
Labels: collisions, Airflow

#722 #615 miovision alert api
  dags/miovision_pull.py
  volumes/miovision/api/pull_alert.py
  volumes/miovision/api/readme.md
  volumes/miovision/sql/README.md
  volumes/miovision/sql/table/create-table-alerts.sql
Labels: enhancement, Miovision

#917 #915 update detector inventory
  volumes/vds/sql/views/create-view-detector_inventory.sql
Labels: RESCU
